=== syeshenko/task3_XML/src/main/resources/Tariff.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">

    <xs:element name="Tariff" type="xs:string"/>

    <xs:element name="id" type="xs:ID">
            <xs:simpleType>
                <xs:restriction base="xs:ID">
                    <xs:pattern value="[t][0-9]+"/>
                </xs:restriction>
            </xs:simpleType>
    </xs:element>

    <xs:element name="Name" type="xs:string"/>

    <xs:element name="Operator_Name" type="xs:string"/>

    <xs:element name="Payroll" type="xs:positiveInteger"/>

    <xs:complexType name="Call_Price">
        <xs:sequence>
            <xs:element name="OutgoingCallToBeelineNumbers" type="xs:positiveInteger" />
            <xs:element name="OutgoingCallToOtherOperators" type="xs:positiveInteger" />
            <xs:element name="OutgoingCallToLandlineNumbers" type="xs:positiveInteger" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="SMS_Price" type="xs:positiveInteger"/>

    <xs:complexType name="Parameters">
        <xs:sequence>
            <xs:element name="FavoriteNumbersAmount" type="xs:positiveInteger"/>
            <xs:element name="BillingIncrementSeconds" type="xs:positiveInteger"/>

            <xs:element name="ActivationFee" type="xs:positiveInteger"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== syeshenko/task3_XML/src/main/resources/Tariff.xml
<?xml version="1.0" encoding="UTF-8"?>
<Tariff xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="Tariff.xsd">

    <id>t1</id>
        <Name>Simple</Name>
        <Operator_Name>Beeline</Operator_Name>
        <Payroll>1000</Payroll>
        <Call_Price>
            <OutgoingCallToBeelineNumbers>5</OutgoingCallToBeelineNumbers>
            <OutgoingCallToOtherOperators>7</OutgoingCallToOtherOperators>
            <OutgoingCallToLandlineNumbers>8</OutgoingCallToLandlineNumbers>
        </Call_Price>
        <SMS_Price>7</SMS_Price>
        <Parameters>
            <FavoriteNumbersAmount>3</FavoriteNumbersAmount>
            <BillingIncrementSeconds>1</BillingIncrementSeconds>
            <ActivationFee>200</ActivationFee>
        </Parameters>


        <id>t2</id>
        <Name>Premium</Name>
        <Operator_Name>Beeline</Operator_Name>
        <Payroll>5000</Payroll>
        <Call_Price>
            <OutgoingCallToBeelineNumbers>0</OutgoingCallToBeelineNumbers>
            <OutgoingCallToOtherOperators>3</OutgoingCallToOtherOperators>
            <OutgoingCallToLandlineNumbers>3</OutgoingCallToLandlineNumbers>
        </Call_Price>
        <SMS_Price>5</SMS_Price>
        <Parameters>
            <FavoriteNumbersAmount>15</FavoriteNumbersAmount>
            <BillingIncrementSeconds>1</BillingIncrementSeconds>
            <ActivationFee>200</ActivationFee>
        </Parameters>


</Tariff>
